import { promises as fs } from 'node:fs';
import path from 'node:path';
import { test as base, expect } from '../fixtures/app-fixtures';
import type { TestInfo } from '@playwright/test';

type DocumentTestParams = {
  testName: string;
  description: string;
  testFile: string;
};

type DocumentationFixtures = {
  documentTest: (params: DocumentTestParams) => Promise<void>;
  _autoDocumentTest: void;
};

const toSlug = (value: string): string =>
  value
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

export const test = base.extend<DocumentationFixtures>({
  _autoDocumentTest: [async ({ documentTest }, use, testInfo: TestInfo) => {
    await documentTest({
      testName: testInfo.title,
      description: `Auto-generated E2E documentation for test "${testInfo.title}".`,
      testFile: testInfo.file,
    });

    await use();
  }, { auto: true }],

  documentTest: async ({}, use) => {
    await use(async ({ testName, description, testFile }: DocumentTestParams): Promise<void> => {
      const docsDir = path.resolve(process.cwd(), 'test-documentation');
      await fs.mkdir(docsDir, { recursive: true });

      const slug = toSlug(testName) || 'test-documentation';
      const filePath = path.join(docsDir, `${slug}.md`);
      const now = new Date().toISOString();

      const markdown = [
        `# Test: ${testName}`,
        '',
        '## Description',
        description,
        '',
        '## Test File',
        `\`${testFile}\``,
        '',
        '## Created At',
        now,
        '',
        '---',
        '*Automatically generated by Playwright test documentation hook.*',
        '',
      ].join('\n');

      await fs.writeFile(filePath, markdown, 'utf8');
      console.log(`Documentation created: ${filePath}`);
    });
  },
});

export { expect };
